[font]
normal      = { family="VictorMono NFM", style="Medium" } # Regular
bold        = { family="VictorMono NFM", style="Bold" }
italic      = { family="VictorMono NFM", style="MediumOblique" }
bold_italic = { family="VictorMono NFM", style="SemiBoldOblique" }
size = 14.0

# [window]
# decorations = "None"

[colors]
normal.black   = "#393552"
bright.black   = "#6e6a86"
normal.red     = "#eb6f92"
bright.red     = "#eb6f92"
normal.green   = "#3e8fb0"
bright.green   = "#3e8fb0"
normal.yellow  = "#f6c177"
bright.yellow  = "#f6c177"
normal.blue    = "#9ccfd8"
bright.blue    = "#9ccfd8"
normal.magenta = "#c4a7e7"
bright.magenta = "#c4a7e7"
normal.cyan    = "#ea9a97"
bright.cyan    = "#ea9a97"
normal.white   = "#e0def4"
bright.white   = "#e0def4"
# cursor         = { text = "#000000", cursor = "#00ff00" }
# vi_mode_cursor = { text = "#000000", cursor = "#00ff00" }

[selection]
save_to_clipboard = true

[cursor]
# style          = { shape="Beam",  blinking="Always" } # see .bashrc, I use escape codes instead, so it does not reset when exiting from vim or similar `\e[6 q\`
style          = { shape="Block", blinking="Always" }
vi_mode_style  = { shape="Block", blinking="Always" }
blink_interval = 300
blink_timeout  = 0

# [terminal]
# shell = { program = "tmux" }

[keyboard]
bindings = [
    { key="Escape", mods="Control", action="ToggleViMode" },
    # { key="U", mods="Control|Shift", action="ScrollHalfPageUp" },
    # { key="D", mods="Control|Shift", action="ScrollHalfPageDown" },
    # { key="Y", mods="Control|Shift", action="ScrollLineUp" },
    # { key="E", mods="Control|Shift", action="ScrollLineDown" },
    # { key="Up", mods="Control|Shift", action="ScrollToTop" },
    # { key="Down", mods="Control|Shift", action="ScrollToBottom" },
    # { key="?", mods="Control|Shift", action="SearchBackward" },
    
    # tmux is a special guy...
    { key = "0", mods = "Control", chars = "\x1b[27;5;48~" },
    { key = "1", mods = "Control", chars = "\x1b[27;5;49~" },
    { key = "2", mods = "Control", chars = "\x1b[27;5;50~" },
    { key = "3", mods = "Control", chars = "\x1b[27;5;51~" },
    { key = "4", mods = "Control", chars = "\x1b[27;5;52~" },
    { key = "5", mods = "Control", chars = "\x1b[27;5;53~" },
    { key = "6", mods = "Control", chars = "\x1b[27;5;54~" },
    { key = "7", mods = "Control", chars = "\x1b[27;5;55~" },
    { key = "8", mods = "Control", chars = "\x1b[27;5;56~" },
    { key = "9", mods = "Control", chars = "\x1b[27;5;57~" },
    { key = ";", mods = "Control", chars = "\x1b[27;5;59~" },
]
